### ISSUE TITLE
権限管理の実装

### ISSUE THREAD

**Issue by ras0q** [traPtitech/traPortfolio#129]

**Comment by Ras96** [comment]
- [ ] 本名公開の有無
- [ ] portalとの連携
- [ ] 一部エンドポイントでtraP外のアクセスを切る(caddyで設定？)

**Comment by ras0q** [comment]
リアルタイムでフロントエンドから取るのは難しいため現状portalのデータをキャッシュしているように事前にtraPortfolio側でデータを取得するようにする

ここらへんの話
https://q.trap.jp/messages/2c918d02-7d4a-4758-bcf0-1a381f1867c1

**Comment by ras0q** [comment]
Portalはv2でOIDCが実装されたら各ユーザーがtraPortfolioがPortalのユーザー情報にアクセスすることを認可して取得した情報をDBに詰めておくと良さそう

https://q.trap.jp/messages/6e226ecd-83e0-47dc-a2e7-708348ebfe38

**Comment by ras0q** [comment]
一旦優先度下げる

**Comment by ras0q** [comment]
#576に任せる
