### ISSUE TITLE
:bug: GET /users/:id/accountsのレスポンスの型がswaggerと異なる

### ISSUE THREAD

**Issue by Ras96** [traPtitech/traPortfolio#152]
GET /users/:idなども同様

[swaggerでのAccountの定義](https://github.com/traPtitech/traPortfolio/blob/1af42a819c03900055d417a6362d6bb5293ad3d1/docs/swagger/traPortfolio.v1.yaml#L829-L848)と[domain/user.goでの定義](https://github.com/traPtitech/traPortfolio/blob/1af42a819c03900055d417a6362d6bb5293ad3d1/domain/user.go#L15-L19)が異なるため起きている
domain.Accountをそのまま返しているため先頭文字が大文字になってたりするのも直したい

---
```json
[
  {
    "id": "string",
    "type": 0,
    "prPermitted": true,
    "url": "string"
  }
]
```
が欲しいが
```json
[
  {
    "ID": "213dce73-7b7d-4bdb-b25c-656f9c2a08d4",
    "Type": 0,
    "PrPermitted": false
  }
]
```
が返ってくる

---
```json
[
  {
    "id": "213dce73-7b7d-4bdb-b25c-656f9c2a08d4",
    "name": "hoge", // twitterとかのアカウント名 serviceIDとかのほうがいいかも
    "type": 0,
    "prPermitted": false,
    "url": "https://twitter.com"
  }
]
```
が返るのが良さそう

**Comment by Hosshii** [comment]
多分handlerでレスポンス用の方を定義するのが良いと思います（やってるところとやってないところがある）
