### ISSUE TITLE
ステージング建てる

### ISSUE THREAD

**Issue by Hosshii** [traPtitech/traPortfolio#173]

**Comment by Hosshii** [comment]
1. 外部サービスのモックを使って動くモードを作る
2. それができたもしくはできる目処が立ったら、ステージングを建てるためにnssにpr出す
3. dbとかの設定をするために、リーダーに言う

**Comment by Ras96** [comment]
1はexample書いてから<https://github.com/stoplightio/prism>のstatic使えばよさそうですかね
>ステージングで使うならprismのdynamicでmockすると固定じゃない値が帰ってきて不整合おきまくりませんか？
(staticでやるなら今度はexampleが書いてなくてレスポンス返ってこなさそう)
https://github.com/traPtitech/traPortfolio/pull/99#issuecomment-888109453

2はすでに追加してあるのでよさそうだったら実装してリーダーにお願いします

**Comment by Ras96** [comment]
↑これ[traQ/v3-api.yaml at master · traPtitech/traQ](https://github.com/traPtitech/traQ/blob/master/docs/v3-api.yaml)とか変えないとそうですね、m011に置くときにすでに実装してある[mock_external](https://github.com/traPtitech/traPortfolio/tree/main/interfaces/external/mock_external)とかに切り替えられればいい感じですか？

**Comment by Hosshii** [comment]
書き換えるか、mock_external使うようにするかのどっちかだと思います

起動時にオプションとかでモック使うようにできるようにするっていう意味です

**Comment by Ras96** [comment]
今環境変数で管理してるので、フラグで管理すればいいですかね、あとでprだします

**Comment by Hosshii** [comment]
なんか今の状態でも`APP_ENV`を`development`にするとモックになる気がするので今のままでも大丈夫かもしれない

**Comment by Ras96** [comment]
一時的に使うものじゃないので環境変数のほうがいい気がしてきました

DBの設定はm011に立ったDBに対して`go run main.go -migrate`してサンプルデータ入れればよさそうですか？

**Comment by Hosshii** [comment]
-migrateしただけだとサンプルデータは入らないので、サンプルデータも作ったほうが良いかもです

**Comment by Ras96** [comment]
migrateして、それからサンプルデータを、、の意図でした:pray:
どっかにsqlファイル置くのがいいと思っているのですがdev/以下とかでいいですか？

**Comment by Hosshii** [comment]
それで大丈夫です

**Comment by Ras96** [comment]
立てたのでclose
https://portfolio-dev.trapti.tech/api/v1/ping
