### ISSUE TITLE
名前変更

### ISSUE THREAD

**Issue by Hosshii** [traPtitech/traPortfolio#181]
api
- contest内のteamをcontestTeamにする（型名を変更する。エンドポイントはこのままでいい）
- groupをteamにする

**Comment by grkon03** [comment]
@Hosshii 型名, 構造体の変数名などを変更してみたのですが、この issue はこういうことであっていますか？(このブランチの直近の 2 commit を見てもらえると助かります)

**Comment by Hosshii** [comment]
https://github.com/traPtitech/traPortfolio/tree/refactor/change_name_team

**Comment by Hosshii** [comment]
その認識で大丈夫です！

**Comment by Hosshii** [comment]
あと、oapi_types_gen.goは https://github.com/traPtitech/traPortfolio/blob/main/docs/swagger/traPortfolio.v1.yaml このファイルをもとに自動生成されているので、oapi_types_gen.goを直接いじるのではなくtraPortfolio.v1.yamlを変更して自動生成するようにしてほしいです:pray:

**Comment by grkon03** [comment]
了解です！
