### ISSUE TITLE
semester考える

### ISSUE THREAD

**Issue by Hosshii** [traPtitech/traPortfolio#187]

**Comment by Hosshii** [comment]
具体的にどうするか決まってないので
https://github.com/traPtitech/traPortfolio/blob/6f3bf873b1de2b795fd01803746124346482c456/interfaces/handler/project.go#L16

**Comment by Ras96** [comment]
これ現状データベースに突っ込むときに変換するのに使ってるんですが、ちょっと冗長ですがdatetimeに直すんじゃなくてそのまま`since_year` `since_semester(0or1)`みたいに持っちゃうのがいい気もしてます
