### ISSUE TITLE
domainでエラーを返すかどうか考える

### ISSUE THREAD

**Issue by Hosshii** [traPtitech/traPortfolio#195]
他にもできてない部分が多いので今すぐ変更するのは難しいと思うんですが、domain.Durationを作るときにIsValidのチェックもしたさがないですか？NewYear...でエラーも返すようにする感じです。
そうすると他の部分でこれを直接使ってるところが面倒になりますが...(MustMake...みたいなのを作ればいいかもしれない)

_Originally posted by @Hosshii in https://github.com/traPtitech/traPortfolio/pull/192#discussion_r786132312_

**Comment by ras0q** [comment]
今考えたらエラーを返すかboolでチェックすれば良さそう
必要になったら都度実装
