### ISSUE TITLE
外部APIの呼び出し箇所を統一する

### ISSUE THREAD

**Issue by Ras96** [traPtitech/traPortfolio#212]
userとかeventはrepositoryで呼んでる
https://github.com/traPtitech/traPortfolio/blob/65724049872c6efda9c938d99795c2672806e44b/interfaces/repository/user_impl.go#L38-L41

projectはserviceで呼んでる
https://github.com/traPtitech/traPortfolio/blob/65724049872c6efda9c938d99795c2672806e44b/usecases/service/project.go#L48-L51

現状[knoQ_impl.go](https://github.com/traPtitech/traPortfolio/blob/main/interfaces/repository/knoQ_impl.go)とかがどこからも呼ばれなくなってしまったので消すかserviceで呼んで使うか統一したいです

**Comment by Ras96** [comment]
#211

**Comment by Ras96** [comment]
個人的には今のuser側に合わせちゃっていいと思ってます(project側を変える)

**Comment by Hosshii** [comment]
knoqはGetByUserIDだけ使われてると思います

**Comment by Hosshii** [comment]
僕もそれでいいと思います。
現状repositoryから帰ってくるやつにはrealnameが含まれていなくてあんまり整合性がないので
