### ISSUE TITLE
フィールド名、メソッド名の統一

### ISSUE THREAD

**Issue by ras0q** [traPtitech/traPortfolio#233]
#135 と似てるけど

- [ ] フィールド名だと`api`とか`repo`みたいな汎用的なものは変えたほうがよさそう
- [ ] handlerで`srv`と`service`が混在してるので統一する
- [ ] `GetAll`みたいなメソッドもファイルによって名前が違うのである程度統一する

**Comment by ras0q** [comment]
レシーバーは1文字がいい

**Comment by 20jun01** [comment]
srvはinterfaces/handler/contest, event, group, user
serviceはproject
引数がsとserviceが混在してそう

**Comment by 20jun01** [comment]
infraのGetAllとかは統一されてそうです
serviceのGet~はGroupだけGetAllGroupsで他はGet~sです(handlerだとGetGroups)

**Comment by ras0q** [comment]
調査ありがとうございます:god:

> apiは修正済みそう。変数名と引数しか使われてない repoも変数と引数以外ではusecase/service以下のファイルで下みたいに使われてます
> 
> ```
> type contestService struct {
> 	repo repository.ContestRepository
> }
> ```

これは複数のrepoを扱うことがあるのでcontestとかの方が好ましいです

> srvはinterfaces/handler/contest, event, group, user serviceはproject 引数がsとserviceが混在してそう

これはsがいいかな

> infraのGetAllとかは統一されてそうです serviceのGet{target}はGroupだけGetAllGroupsで他はGet{target}sです(handlerだとGetGroups)

これちょっと気になってました、後者に合わせていいと思います
何ならinfraもGetTraqUsersとかの方がいいのかもしれない
