### ISSUE TITLE
handlerの構造体のメンバ変数の命名がわかりにくい

### ISSUE THREAD

**Issue by 0214sh7** [traPtitech/traPortfolio#256]
handler.AccountのIdがuuidでhandler.AddAccountのIdがstringで、混乱が生じている
user idかuuidかgroup idの区別も欲しい

**Comment by 0214sh7** [comment]
handler.Accountとhandler.AddAccountを混同してカスになりました

**Comment by Ras96** [comment]
`handler.Account`と同じくとりあえず`Name`でいいと思います
