### ISSUE TITLE
util/mockdata/model.goのモデルを`CloneMockHoge`に統一する

### ISSUE THREAD

**Issue by ras0q** [traPtitech/traPortfolio#267]
https://github.com/traPtitech/traPortfolio/blob/ff5d52380d1e0cd80be1fb2dce76b2a742d231b6/util/mockdata/model.go#L13-L14
2つあるが下に統一する
無名関数やめて普通の関数定義でもいいかも

**Comment by Hosshii** [comment]
今のprっていうのは#265 です
