### ISSUE TITLE
PATCH /users/:userID/accounts/:accountIDでリクエストボディが空だと204が返る

### ISSUE THREAD

**Issue by ras0q** [traPtitech/traPortfolio#292]
仕様、、、？

**Comment by Ras96** [comment]
これtransactionの中に入れてもいいかもだけど処理の流れがきもいかも
https://github.com/traPtitech/traPortfolio/blob/58bf7b34c43a3f8900f1d71a00d01c94d30d64f5/interfaces/repository/user_impl.go#L308-L310

**Comment by ras0q** [comment]
仕様です
