### ISSUE TITLE
DurationはUserDurationを包含しているべき

### ISSUE THREAD

**Issue by 0214sh7** [traPtitech/traPortfolio#317]
プロジェクト期間はユーザーがプロジェクトに所属している(していた)期間を包含しているはずなので、それに対応したテストを作成したい

https://github.com/traPtitech/traPortfolio/blob/5c3c6df8d564f28d018ec48bf50496209c4fd60a/interfaces/handler/user_test.go#L903-L920

**Comment by ras0q** [comment]
```go
func (p *ProjectDeteil) DurationsIsValid() bool {
```
```go
func (p *ProjectDeteil) DurationsIsValid() error {
```
のどっちかで書くとよさそう

**Comment by ras0q** [comment]
プロジェクトのDurationと比較する必要があるので`(r AddProjectMembersRequest) Validate()`ではvalidateできない
domainに書いてserviceでvalidateする必要がありそう
