### ISSUE TITLE
infrastructure.SQLHandler#Errorでエラーの変換を行うようにする

### ISSUE THREAD

**Issue by Ras96** [traPtitech/traPortfolio#332]
現状
https://github.com/traPtitech/traPortfolio/blob/81660c070fea2b9dcc1e404e3b036053af173795/interfaces/repository/error.go#L10-L15
みたいにしてるけどgormに依存してるので↓で変換して返すようにする
https://github.com/traPtitech/traPortfolio/blob/81660c070fea2b9dcc1e404e3b036053af173795/infrastructure/sqlhandler.go#L130-L132

**Comment by Hosshii** [comment]
Error()関数で返すエラーはinterface側で定義して、その実装はinfra出するのが良さそうですね（他の部分のinterfaceと実装の分離と同じ感じで）

**Comment by Ras96** [comment]
Error()関数で返すエラーっていうのは https://github.com/traPtitech/traPortfolio/blob/main/usecases/repository/errors.go とは別のものを指してますか？あんまり理解できてないかもです

**Comment by Hosshii** [comment]
それですね。
自分が勘違いしててerrorの定義がまだないかと思ってました。
