### ISSUE TITLE
結合テストのbuild tagsを外す

### ISSUE THREAD

**Issue by Ras96** [traPtitech/traPortfolio#350]
あまりbuild tagsで結合テスト書いてるところがなかったので

- [x] `make test-integration-db`を
```
$ go test $(go list ./... | grep -v "integration_test")
```
みたいな感じにする

- [ ] handler.convertErrorがprivateなので
- 2XX以外のときのエラーをassertしないようにする
  - 今は`interface{}`型になってる`tt.want`を2XXのときの型に限定できる
- handler.convertErrorを publicにする

のどちらかを行う

**Comment by Ras96** [comment]
↓で`.Error()`を引数に渡してるので`errors.Is`でうまく比較できない(`.Error()`をしないと`message: <nil>`になるためこれは必要)
個人的には前者でいいかなと思ってます
https://github.com/traPtitech/traPortfolio/blob/8877f030f1bdd1e16bd585788314b70bd8ce917f/interfaces/handler/errors.go#L22-L23

**Comment by Hosshii** [comment]
このconvertErrorってbuild tagtとは独立したものですかね？

**Comment by Ras96** [comment]
完全に独立ではないのですが(handler/export.goがビルドに含まれちゃうので)、1個のPRだと大きくなるのと時間がかかりそうだったのでとりあえずタグ外すとこだけにしました
closeじゃなくてrefで指定すればよかったかもです:pray:

**Comment by Hosshii** [comment]
理解しました:kansya:

**Comment by Hosshii** [comment]
エクスポートしたconvertErrorテストで使うんじゃなくて、エラーの文字列をベタ書きしてもいい気がします
