### ISSUE TITLE
アカウントのurlのバリデーションを厳しくする

### ISSUE THREAD

**Issue by ras0q** [traPtitech/traPortfolio#359]
twitterアカウントはhttps://twitter.comで始まるようにとか

**Comment by mehm8128** [comment]
Twitter、Facebook、Github、Qiita、Zenn、AtCoder、SoundCloudはdisplayNameからURLを生成可能なので、URLは空で送信される。
その他はHomePageとBlog以外は上でコメントされているようにURLのバリデーションをするようにする。

**Comment by mehm8128** [comment]
やっぱりURL生成可能なものはクライアントで生成して送ってもらった方がきれいになりそう

**Comment by Ras96** [comment]
たしかにきれいにはなるんですがバックエンドでバリデーションを何も行わないとなるとAPIを直で叩かれたときに困るのできつそう

**Comment by mehm8128** [comment]
クライアントで生成してかつバリデーションも全部行うようにするならよさそうですかね？

**Comment by Ras96** [comment]
そっちのほうがURL空よりいいですね:+1:
