### ISSUE TITLE
mockdataの返り値を構造体から構造体の配列に変える

### ISSUE THREAD

**Issue by Ras96** [traPtitech/traPortfolio#388]
単数だと使いづらそう

**Comment by mehm8128** [comment]
多分この3つですかね

- [ ] CloneHandlerMockContest→CloneHandlerMockContestDetails
- [ ] CloneHandlerMockContestTeam→CloneHandlerMockContestTeams
- [ ] CloneHandlerMockGroup→CloneHandlerMockGroups

必要に応じて`model.go`も配列にしたり要素増やしたり
