### ISSUE TITLE
migration時に`*gorm.DB`が汚染されていそう？

### ISSUE THREAD

**Issue by mazrean** [traPtitech/traPortfolio#407]
https://github.com/traPtitech/traPortfolio/blob/dff3d16b1b13fb3327c42f577b88715dac0626b5/infrastructure/migration/migrate.go#L11 のmigrationで`*gorm.DB`をsessionを切らずに使っており、この関数を呼び出す前にもsessionを新しく切っていないような気がする。
これだと、指定なしの場合に`migrations`テーブルが操作される危険があるので、sessionを切った状態でmigrationをした方が良さそう。

traP Collectionで似たようなことをしたら大元の`*gorm.DB`が`migrations`テーブルが対象になった状態に汚染され、全てのクエリが壊れたので一応報告しておきます。
traPortfolioで今の所問題になっていない原因とかは調べていないけど、もしかしたらtraPortfolioでは何らかの理由で汚染の影響が防がれていたりするのかも。

**Comment by Ras96** [comment]
今のところ大丈夫そう
一旦クローズします
