### ISSUE TITLE
service層を消す

### ISSUE THREAD

**Issue by ras0q** [traPtitech/traPortfolio#431]
handlerからrepositoryに受け渡すだけになってるので消してよさそう

**Comment by Ras96** [comment]
やること

- handlerからrepositoryのメソッドを呼び出す
- handlerの単体テストでrepositoryのモックを呼び出すようにする
- service層消す

**Comment by ras0q** [comment]
- repositoryのリレーしてるだけのやつはそのままhandlerからrepository呼ぶ
- 少し処理が書いてあるやつは(とりあえず)handlerに処理を移す
  - 今service層にかいてあるやつでビジネスロジックって呼べるやつはあんまりなさそうなので問題なさそう
