### ISSUE TITLE
GET /users/:id/contestsでContestTeamの情報が返ってる

### ISSUE THREAD

**Issue by Ras96** [traPtitech/traPortfolio#440]
//q.trap.jp/messages/99db4ce8-1d1e-4873-b561-5163d4e9f9fa

**Comment by mehm8128** [comment]
方針メモ
現在、チームの情報とコンテスト名を返している
↓逆にする
コンテスト情報と参加したチームid&チーム名を返すようにする(外部向けページの方でチーム名も表示したいため)

**Comment by Ras96** [comment]
とりあえずswaggerだけは直したので実装は早めに書く
