### ISSUE TITLE
ディレクトリ構造をmarkdownで書く

### ISSUE THREAD

**Issue by ras0q** [traPtitech/traPortfolio#466]
drawioで管理してたけど変更しづらいのでmarkdownファイル上にmermaidかgraphvizで書くとよさそう

**Comment by H1rono** [comment]
- mermaidを使う(markdownに埋め込んでGitHub上で表示できるため)
- 図が古いので関係を作り直す

メモリンク:

- https://zenn.dev/minato_seagull/articles/93e66469b3e8d2
- https://zenn.dev/junkawa/articles/zenn-mermaidjs-theme-config
- https://note.com/_kikiyo_/n/n67ca638d8c5c
