### ISSUE TITLE
イベントの公開設定の実装

### ISSUE THREAD

**Issue by ras0q** [traPtitech/traPortfolio#568]

**Comment by ras0q** [comment]
ここではeventLevelから公開、名前の未公開、非公開を実装

**Comment by H1rono** [comment]
https://github.com/traPtitech/traPortfolio/blob/8e64b021c2b39d5fa585fd0bb5a954463ce7386c/domain/event.go#L37-L42
ここのLevel設定を`GET /events`と`GET /events/:id`のレスポンスに反映させればいいってことであってますか？

**Comment by ras0q** [comment]
ってことです
GET /users/:id/eventsもかな
domainに表示を制御するメソッドを生やすのと、dbから取得時にwhere制限かけるのが良さそう？

**Comment by H1rono** [comment]
> domainに表示を制御するメソッドを生やす

↓みたいな関数をdomain/event.goに置くってことですか？

```go
// ApplyEventLevel EventDetailのLevelに応じてEventを返す
func ApplyEventLevel(e EventDetail) optional.Of[Event] {
	var res Event
	switch e.Level {
	case EventLevelAnonymous:
		res = e.Event
		res.Name = ""
	case EventLevelPublic:
		res = e.Event
	case EventLevelPrivate:
	default:
		return optional.Of[Event]{}
	}
	return optional.From(res)
}
```

> dbから取得時にwhere制限かける

↓になんか追記するってことですか？

https://github.com/traPtitech/traPortfolio/blob/8e64b021c2b39d5fa585fd0bb5a954463ce7386c/interfaces/repository/event_impl.go#L24-L42

**Comment by ras0q** [comment]
whereの方はそういうことです

domainの方はあんまりいい方法思いついてないけどユーザーの本名みたいにフィールドをpritateにして
```go
func (e EventDetail)Place()string {
  return e.place
}
```
とかが良さそうです

**Comment by ras0q** [comment]
別の話だけど匿名っていうのはOpenapiを見る限り主催者名が匿名ってことですね

**Comment by ras0q** [comment]
あと今のままだとdomain.Eventはlevelを持たないから出来ても公開(返す)か非公開(返さない)しか表現出来ないな

**Comment by ras0q** [comment]
descriptionはmdのリンクとか貼ってあること多いから一括で公開設定を反映するのはリスキーなのかもしれん
userみたいにdescriptionはtraPortfolio側で持つのもありかも

**Comment by H1rono** [comment]
> ユーザーの本名みたいにフィールドをpritateにして

隠すのは`HostName`であってますか(念の為確認)

> 匿名っていうのはOpenapiを見る限り主催者名が匿名ってことですね

`EventLevelAnonymous`は`Event`構造体に対しては`EventLevelPublic`と同様に作用するということですか？となると、

> あと今のままだとdomain.Eventはlevelを持たないから出来ても公開(返す)か非公開(返さない)しか表現出来ないな

これは正しい挙動に見えます、`Event`は`EventDetail`に対してdetail-omittedなので
`Level`がdetailか否かを考える必要がありそう

> userみたいにdescriptionはtraPortfolio側で持つのもありかも

このissueでやるかどうかも含めて検討したいですね
descriptionのデフォルト値をknoQのものにしてtraPortfolio側で持つ+Levelにdescriptionの可視性もいじるオプションを入れる、とか？

**Comment by ras0q** [comment]
> 隠すのはHostNameであってますか(念の為確認)

あってます
ただPlaceもどうしようか迷ってます(anonymousでも公開してよい？)

> これは正しい挙動に見えます、EventはEventDetailに対してdetail-omittedなので
Levelがdetailか否かを考える必要がありそう

まあ想定挙動としていい気がする
LevelはこのPRではEventDetailに入れたままでいいかな

> このissueでやるかどうかも含めて検討したいですね
descriptionのデフォルト値をknoQのものにしてtraPortfolio側で持つ+Levelにdescriptionの可視性もいじるオプションを入れる、とか？

別PRでいいです
デフォルトknoQのにしてmdに勝手にアクセスされるのが辛いのでknoQのdescriptionは使わないようにしたいですね

いっそ公開非公開を決める設定がかなり多くなりそうなので↓を生やしてもいいのかなと思いました
generatorで生成できる気しないからgenericsは厳しそうだけど

```json
"hostname": {
  "value": [{},{},{}]
  "isPublic": true
}
```
```go
type WithPublic[T any] struct {
    Value T
    IsPublic bool
}
```

**Comment by ras0q** [comment]
あと自分のイベントは全部見れるエンドポイントがないと公開設定をしようがないことに気づいた
