### ISSUE TITLE
injector動かしたい

### ISSUE THREAD

**Issue by H1rono** [traPtitech/traPortfolio#608]
この依存関係を/infra以下に置くと絡まりそう、という感じ

https://github.com/traPtitech/traPortfolio/blob/d2d2383fafe187343b0f8e0626ad503b4dc6a1b7/infrastructure/injector.go#L3-L11

/injectorとかに動かしたい

**Comment by ras0q** [comment]
例えばmain.goをcmd/に動かしてここにinjectorも置くとかだと自然かも
