### ISSUE TITLE
イベント一覧APIに公開範囲を追加

### ISSUE THREAD

**Issue by H1rono** [traPtitech/traPortfolio#621]
> Dashboardイベント一覧ページでのフィルタリングに使いたい

https://q.trap.jp/messages/cb8c879f-5ef9-4620-b80c-33503237bc22

**Comment by H1rono** [comment]
[traPortfolio.v1.yaml](https://github.com/traPtitech/traPortfolio/blob/a009598728441bbe1ac64e484c58e827fb147786/docs/swagger/traPortfolio.v1.yaml)とハンドラー実装を書き換えればいいかな、とりあえずPR出します

**Comment by H1rono** [comment]
domain変わるのか、もうちょいでかそう

**Comment by ras0q** [comment]
ref https://github.com/traPtitech/traPortfolio/issues/571

**Comment by H1rono** [comment]
確かに
ただ、EventDetailにあってEventにないフィールドそれぞれに対して公開/非公開を考えるのでよさそう
Eventそのものを公開するかどうかを`eventLevel`フィールドで表す？

**Comment by H1rono** [comment]
というか、そもそも非公開のイベントを一覧に含めてはいけないか

**Comment by H1rono** [comment]
`自分のイベント & 非公開のもの` らへんを他と区別するのにlevelが必要になるな

**Comment by ras0q** [comment]
そうなるとadmin APIを追加って方になるかも？

https://github.com/traPtitech/traPortfolio/issues/570

**Comment by ras0q** [comment]
> ただ、EventDetailにあってEventにないフィールドそれぞれに対して公開/非公開を考えるのでよさそう

今からこれやるの結構きついから1回考えなくていいかも
既存のeventLevel(hostname匿名設定は含む)だけ考えればいいかな

**Comment by H1rono** [comment]
Admin周りは https://github.com/traPtitech/traPortfolio/issues/576 絡んでる
